// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectoFinalV2.Models;

#nullable disable

namespace projectoFinalV2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250513210612_JsonListConversion")]
    partial class JsonListConversion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("projectoFinalV2.Models.Film", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("locations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("movie_banner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("original_title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("original_title_romanised")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("people")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("producer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("release_date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("rt_score")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("running_time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vehicles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("projectoFinalV2.Models.People", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("age")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("eye_color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("films")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hair_color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
